Repository boostcampth/boostcamp3_F, pull requests merged in 2019-02, with the labels that each got.

#49 코드 리팩토링
  app/src/main/java/com/boostcamp/travery/base/BaseActivity.kt
  app/src/main/java/com/boostcamp/travery/base/BaseAdapter.kt
  app/src/main/java/com/boostcamp/travery/base/BaseViewHolder.kt
  app/src/main/java/com/boostcamp/travery/base/OnClickListeners.kt
  app/src/main/java/com/boostcamp/travery/main/adapter/CourseListAdapter.kt
  app/src/main/java/com/boostcamp/travery/search/adapter/UserActionSearchAdapter.kt
Labels: 심플

#50 (#45) 경로 상세보기 MVVM 전환
  app/src/main/java/com/boostcamp/travery/base/BaseActivity.kt
  app/src/main/java/com/boostcamp/travery/coursedetail/CourseDetailActivity.kt
  app/src/main/java/com/boostcamp/travery/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/com/boostcamp/travery/coursedetail/UserActionLeftListAdapter.kt
  app/src/main/java/com/boostcamp/travery/coursedetail/UserActionTopListAdapter.kt
  app/src/main/java/com/boostcamp/travery/data/AppDataManager.kt
  app/src/main/java/com/boostcamp/travery/utils/BindingUtils.kt
  app/src/main/java/com/boostcamp/travery/utils/Extensions.kt
  app/src/main/res/layout/activity_course_detail.xml
Labels: 리팩토링

#59 (#58) 새로운 베이스 어댑터 생성
  app/src/main/java/com/boostcamp/travery/base/ObservableRecyclerViewAdapter.kt
Labels: 심플

#60 (#51) 코스 기록화면 xml 수정 및 활동 추가 화면
  .idea/codeStyles/codeStyleConfig.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/travery/Constants.kt
  app/src/main/java/com/boostcamp/travery/MyGlideModule.kt
  app/src/main/java/com/boostcamp/travery/data/AppDataManager.kt
  app/src/main/java/com/boostcamp/travery/main/MainActivity.kt
  app/src/main/java/com/boostcamp/travery/save/ObservableRecyclerViewAdapter.kt
  app/src/main/java/com/boostcamp/travery/save/UserActionImageListAdapter.kt
  app/src/main/java/com/boostcamp/travery/save/UserActionSaveActivity.kt
  app/src/main/java/com/boostcamp/travery/save/UserActionSaveViewModel.kt
  app/src/main/java/com/boostcamp/travery/utils/BindingUtils.kt
  app/src/main/res/drawable/ic_add_circle_black_24dp.xml
  app/src/main/res/layout/activity_course_save.xml
  app/src/main/res/layout/activity_save_user_action.xml
  app/src/main/res/layout/item_useraction_save.xml
  app/src/main/res/layout/item_useraction_save_image.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 자세한 리뷰 필요

#72 (#63) 활동 상세 화면
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/travery/Constants.kt
  app/src/main/java/com/boostcamp/travery/base/BaseAdapter.kt
  app/src/main/java/com/boostcamp/travery/save/UserActionSaveViewModel.kt
  app/src/main/java/com/boostcamp/travery/search/SearchResultActivity.kt
  app/src/main/java/com/boostcamp/travery/useractiondetail/UserActionDetailActivity.kt
  app/src/main/java/com/boostcamp/travery/useractiondetail/UserActionDetailViewModel.kt
  app/src/main/java/com/boostcamp/travery/useractiondetail/UserActionImageAdapter.kt
  app/src/main/java/com/boostcamp/travery/utils/BindingUtils.kt
  app/src/main/res/drawable/bg_hashtag.xml
  app/src/main/res/drawable/ic_hashtag.png
  app/src/main/res/drawable/ic_location_on_black_24dp.xml
  app/src/main/res/drawable/ic_photo_library_black_24dp.xml
  app/src/main/res/layout/activity_save_user_action.xml
  app/src/main/res/layout/activity_user_action_detail.xml
  app/src/main/res/layout/item_useraction_detail_image.xml
  app/src/main/res/values/styles.xml
Labels: 기능추가, 레이아웃

#85 Feature/bcf 69
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/travery/data/model/Suggestion.kt
  app/src/main/java/com/boostcamp/travery/mapservice/MapTrackingService.kt
  app/src/main/java/com/boostcamp/travery/mapservice/SuggestListAdapter.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingActivity.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingViewModel.kt
  app/src/main/java/com/boostcamp/travery/mapservice/savecourse/CourseSaveViewModel.kt
  app/src/main/res/drawable/ic_add_alert_black_24dp.xml
  app/src/main/res/drawable/ic_add_alert_red_24dp.xml
  app/src/main/res/drawable/ic_add_white_24dp.xml
  app/src/main/res/drawable/ic_directions_run_black_24dp.xml
  app/src/main/res/drawable/ic_stop_black_24dp.xml
  app/src/main/res/layout/activity_tracking.xml
  app/src/main/res/layout/item_dialog_footer.xml
  app/src/main/res/layout/item_suggest_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 자세한 리뷰 필요

#113 (#99) 지도 위에 활동 목록 표시
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/travery/base/BaseActivity.kt
  app/src/main/java/com/boostcamp/travery/data/UserActionDataSource.kt
  app/src/main/java/com/boostcamp/travery/data/local/source/UserActionLocalDataSource.kt
  app/src/main/java/com/boostcamp/travery/data/repository/UserActionRepository.kt
  app/src/main/java/com/boostcamp/travery/main/MainActivity.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingActivity.kt
  app/src/main/java/com/boostcamp/travery/search/SearchResultActivity.kt
  app/src/main/java/com/boostcamp/travery/useraction/detail/UserActionDetailActivity.kt
  app/src/main/java/com/boostcamp/travery/useraction/detail/UserActionDetailViewModel.kt
  app/src/main/java/com/boostcamp/travery/useraction/detail/UserActionImageAdapter.kt
  app/src/main/java/com/boostcamp/travery/useraction/list/UserActionListActivity.kt
  app/src/main/java/com/boostcamp/travery/useraction/list/UserActionListViewModel.kt
  app/src/main/java/com/boostcamp/travery/useraction/list/cluster/ClusterItemUserAction.kt
  app/src/main/java/com/boostcamp/travery/useraction/list/cluster/ClusterRenderer.kt
  app/src/main/java/com/boostcamp/travery/useraction/list/cluster/MultiDrawble.kt
  app/src/main/java/com/boostcamp/travery/useraction/save/UserActionImageListAdapter.kt
  app/src/main/java/com/boostcamp/travery/useraction/save/UserActionSaveActivity.kt
  app/src/main/java/com/boostcamp/travery/useraction/save/UserActionSaveViewModel.kt
  app/src/main/java/com/boostcamp/travery/utils/BindingUtils.kt
  app/src/main/res/drawable/empty_marker_image.png
  app/src/main/res/layout/activity_save_user_action.xml
  app/src/main/res/layout/activity_user_action_detail.xml
  app/src/main/res/layout/activity_user_action_list.xml
  app/src/main/res/layout/cluster_profile.xml
  app/src/main/res/layout/item_useraction_save_image.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/dimens.xml
Labels: 자세한 리뷰 필요

#121 TrackingActivity ViewModel 분리하기
  app/src/main/java/com/boostcamp/travery/Constants.kt
  app/src/main/java/com/boostcamp/travery/data/repository/MapTrackingRepository.kt
  app/src/main/java/com/boostcamp/travery/mapservice/MapTrackingService.kt
  app/src/main/java/com/boostcamp/travery/mapservice/SuggestListAdapter.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingActivity.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingViewModel.kt
  app/src/main/java/com/boostcamp/travery/mapservice/savecourse/CourseSaveViewModel.kt
  app/src/main/res/layout/activity_tracking.xml
  app/src/main/res/values/strings.xml
Labels: 도와주세요

#126 trackingviewmodel repository 교체
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingViewModel.kt
  app/src/main/java/com/boostcamp/travery/mapservice/savecourse/CourseSaveViewModel.kt
Labels: 심플

#133 (#117) 메인, 활동 관련 Repository 리팩토링
  app/src/main/java/com/boostcamp/travery/Injection.kt
  app/src/main/java/com/boostcamp/travery/OnItemClickListener.kt
  app/src/main/java/com/boostcamp/travery/base/BaseViewModel.kt
  app/src/main/java/com/boostcamp/travery/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/com/boostcamp/travery/data/AppDataManager.kt
  app/src/main/java/com/boostcamp/travery/data/CourseDataSource.kt
  app/src/main/java/com/boostcamp/travery/data/CourseRepository.kt
  app/src/main/java/com/boostcamp/travery/data/DataManager.kt
  app/src/main/java/com/boostcamp/travery/data/UserActionDataSource.kt
  app/src/main/java/com/boostcamp/travery/data/local/db/AppDatabase.kt
  app/src/main/java/com/boostcamp/travery/data/local/db/AppDbHelper.kt
  app/src/main/java/com/boostcamp/travery/data/local/db/DbHelper.kt
  app/src/main/java/com/boostcamp/travery/data/local/source/CourseLocalDataSource.kt
  app/src/main/java/com/boostcamp/travery/data/local/source/UserActionLocalDataSource.kt
  app/src/main/java/com/boostcamp/travery/data/model/Course.kt
  app/src/main/java/com/boostcamp/travery/data/model/UserAction.kt
  app/src/main/java/com/boostcamp/travery/data/repository/UserActionRepository.kt
  app/src/main/java/com/boostcamp/travery/main/MainActivity.kt
  app/src/main/java/com/boostcamp/travery/main/MainViewModel.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingActivity.kt
  app/src/main/java/com/boostcamp/travery/search/SearchResultActivity.kt
  app/src/main/java/com/boostcamp/travery/search/SearchResultViewModel.kt
  app/src/main/java/com/boostcamp/travery/useraction/list/UserActionListActivity.kt
  app/src/main/java/com/boostcamp/travery/useraction/list/UserActionListViewModel.kt
  app/src/main/java/com/boostcamp/travery/useraction/save/UserActionSaveActivity.kt
  app/src/main/java/com/boostcamp/travery/useraction/save/UserActionSaveViewModel.kt
  app/src/main/java/com/boostcamp/travery/utils/CustomMarker.kt
  app/src/main/java/com/boostcamp/travery/utils/FileUtils.kt
  app/src/main/java/com/boostcamp/travery/utils/NewFileUtils.kt
Labels: 리팩토링

#135 (#134) Geocoding 추가
  app/src/main/java/com/boostcamp/travery/useraction/save/UserActionSaveActivity.kt
  app/src/main/java/com/boostcamp/travery/useraction/save/UserActionSaveViewModel.kt
  app/src/main/res/layout/activity_save_user_action.xml
  app/src/main/res/layout/activity_user_action_detail.xml
  app/src/main/res/layout/item_feed_user_action.xml
  app/src/main/res/values/dimens.xml
Labels: 레이아웃

#137 Map Tracking UI, UX 변경
  app/src/main/java/com/boostcamp/travery/data/repository/MapTrackingRepository.kt
  app/src/main/java/com/boostcamp/travery/mapservice/MapTrackingService.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingActivity.kt
  app/src/main/java/com/boostcamp/travery/mapservice/TrackingViewModel.kt
  app/src/main/java/com/boostcamp/travery/utils/BindingUtils.kt
  app/src/main/res/drawable/history_info_cell.png
  app/src/main/res/drawable/ic_chevron_left_black_24dp.xml
  app/src/main/res/drawable/ic_info_outline_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_none_black_24dp.xml
  app/src/main/res/drawable/ic_stop_black_24dp.xml
  app/src/main/res/drawable/ride_compass_cell.png
  app/src/main/res/drawable/ride_lap.png
  app/src/main/res/drawable/ride_speed_cell.png
  app/src/main/res/drawable/speech_bubble.9.png
  app/src/main/res/drawable/textview_with_red_circle.xml
  app/src/main/res/drawable/walk1.png
  app/src/main/res/drawable/walk2.png
  app/src/main/res/drawable/walk3.png
  app/src/main/res/drawable/walk4.png
  app/src/main/res/drawable/walk5.png
  app/src/main/res/drawable/walk6.png
  app/src/main/res/drawable/walk_anim.xml
  app/src/main/res/layout/activity_tracking.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 레이아웃
